name: releases
on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
jobs:
  tagged-release:
    runs-on: ubuntu-latest
    steps:
      - name: Automatic Releases
      # checkout code
      - name: Checkout code
        uses: actions/checkout@master
      # automatic release
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: "latest"
          automatic_release_tag_prefix: "v"
          prerelease: true
          repo_token: "${{ secrets.GITHUB_TOKEN }}"