name: testing
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
jobs:
  check-test:
    runs-on: ubuntu-latest
    steps:
      - uses: morrisoncole/pr-lint-action@v1.6.1
        with:
          node-version: 18.13.0
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      - run: npm install
      - run: npm run test